/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DNSVerificationInitParameters struct {
}

type DNSVerificationObservation struct {

	// Record type.
	RecordType *string `json:"recordType,omitempty" tf:"record_type,omitempty"`

	// Record the value.
	RecordValue *string `json:"recordValue,omitempty" tf:"record_value,omitempty"`

	// Host record.
	Subdomain *string `json:"subdomain,omitempty" tf:"subdomain,omitempty"`
}

type DNSVerificationParameters struct {
}

type OwnershipVerificationInitParameters struct {
}

type OwnershipVerificationObservation struct {

	// CNAME access, using DNS to resolve the information required for authentication. For details, please refer to Site/Domain Name Ownership Verification . Note: This field may return null, indicating that no valid value can be obtained.
	DNSVerification []DNSVerificationObservation `json:"dnsVerification,omitempty" tf:"dns_verification,omitempty"`
}

type OwnershipVerificationParameters struct {
}

type WorkModeInfosInitParameters struct {

	// Configuration group type. Valid values: l7_acceleration: L7 acceleration configuration group; edge_functions: Edge functions configuration group.
	// Configuration group type. Valid values: `l7_acceleration`: L7 acceleration configuration group; `edge_functions`: Edge functions configuration group.
	ConfigGroupType *string `json:"configGroupType,omitempty" tf:"config_group_type,omitempty"`

	// Work mode. Valid values: immediate_effect: Immediate effect mode; version_control: Version control mode.
	// Work mode. Valid values: `immediate_effect`: Immediate effect mode; `version_control`: Version control mode.
	WorkMode *string `json:"workMode,omitempty" tf:"work_mode,omitempty"`
}

type WorkModeInfosObservation struct {

	// Configuration group type. Valid values: l7_acceleration: L7 acceleration configuration group; edge_functions: Edge functions configuration group.
	// Configuration group type. Valid values: `l7_acceleration`: L7 acceleration configuration group; `edge_functions`: Edge functions configuration group.
	ConfigGroupType *string `json:"configGroupType,omitempty" tf:"config_group_type,omitempty"`

	// Work mode. Valid values: immediate_effect: Immediate effect mode; version_control: Version control mode.
	// Work mode. Valid values: `immediate_effect`: Immediate effect mode; `version_control`: Version control mode.
	WorkMode *string `json:"workMode,omitempty" tf:"work_mode,omitempty"`
}

type WorkModeInfosParameters struct {

	// Configuration group type. Valid values: l7_acceleration: L7 acceleration configuration group; edge_functions: Edge functions configuration group.
	// Configuration group type. Valid values: `l7_acceleration`: L7 acceleration configuration group; `edge_functions`: Edge functions configuration group.
	// +kubebuilder:validation:Optional
	ConfigGroupType *string `json:"configGroupType" tf:"config_group_type,omitempty"`

	// Work mode. Valid values: immediate_effect: Immediate effect mode; version_control: Version control mode.
	// Work mode. Valid values: `immediate_effect`: Immediate effect mode; `version_control`: Version control mode.
	// +kubebuilder:validation:Optional
	WorkMode *string `json:"workMode" tf:"work_mode,omitempty"`
}

type ZoneInitParameters struct {

	// Alias site identifier. Limit the input to a combination of numbers, English, - and _, within 20 characters. For details, refer to the alias site identifier. If there is no such usage scenario, leave this field empty.
	// Alias site identifier. Limit the input to a combination of numbers, English, - and _, within 20 characters. For details, refer to the alias site identifier. If there is no such usage scenario, leave this field empty.
	AliasZoneName *string `json:"aliasZoneName,omitempty" tf:"alias_zone_name,omitempty"`

	// When the Type value is partial/full, the acceleration region of the L7 domain name. The following are the values of this parameter, and the default value is overseas if not filled in. When the Type value is noDomainAccess, please leave this value empty:
	// When the Type value is partial/full, the acceleration region of the L7 domain name. The following are the values of this parameter, and the default value is overseas if not filled in. When the Type value is noDomainAccess, please leave this value empty:
	// - global: Global availability zone.
	// - mainland: Chinese mainland availability zone.
	// - overseas: Global availability zone (excluding Chinese mainland).
	Area *string `json:"area,omitempty" tf:"area,omitempty"`

	// Indicates whether the site is disabled.
	// Indicates whether the site is disabled.
	Paused *bool `json:"paused,omitempty" tf:"paused,omitempty"`

	// The target Plan ID to be bound. When you have an existing Plan in your account, you can fill in this parameter to directly bind the site to the Plan. If you do not have a Plan that can be bound at the moment, please go to the console to purchase a Plan to complete the site creation.
	// The target Plan ID to be bound. When you have an existing Plan in your account, you can fill in this parameter to directly bind the site to the Plan. If you do not have a Plan that can be bound at the moment, please go to the console to purchase a Plan to complete the site creation.
	PlanID *string `json:"planId,omitempty" tf:"plan_id,omitempty"`

	// Tag description list.
	// Tag description list.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Site Access Type. The possible values for this parameter are as follows; if left unspecified, the default value is partial:
	// Site Access Type. The possible values for this parameter are as follows; if left unspecified, the default value is `partial`:
	//
	// - `partial`: CNAME Access;
	// - `full`: NS Access;
	// - `noDomainAccess`: No-Domain Access;
	// - `dnsPodAccess`: DNSPod Managed Access (this mode requires your domain to already be hosted on DNSPod);
	// - `ai`: Edge Inference Access.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Configuration group work mode. Each configuration module of the site can enable version control mode or immediate effect mode according to the configuration group dimension. For details, please refer to Version Management.
	// Configuration group work mode. Each configuration module of the site can enable version control mode or immediate effect mode according to the configuration group dimension. For details, please refer to [Version Management](https://cloud.tencent.com/document/product/1552/113690).
	WorkModeInfos []WorkModeInfosInitParameters `json:"workModeInfos,omitempty" tf:"work_mode_infos,omitempty"`

	// Site name. When accessing CNAME/NS, please pass the second-level domain (example.com) as the site name; when accessing without a domain name, please leave this value empty.
	// Site name. When accessing CNAME/NS, please pass the second-level domain (example.com) as the site name; when accessing without a domain name, please leave this value empty.
	ZoneName *string `json:"zoneName,omitempty" tf:"zone_name,omitempty"`
}

type ZoneObservation struct {

	// Alias site identifier. Limit the input to a combination of numbers, English, - and _, within 20 characters. For details, refer to the alias site identifier. If there is no such usage scenario, leave this field empty.
	// Alias site identifier. Limit the input to a combination of numbers, English, - and _, within 20 characters. For details, refer to the alias site identifier. If there is no such usage scenario, leave this field empty.
	AliasZoneName *string `json:"aliasZoneName,omitempty" tf:"alias_zone_name,omitempty"`

	// When the Type value is partial/full, the acceleration region of the L7 domain name. The following are the values of this parameter, and the default value is overseas if not filled in. When the Type value is noDomainAccess, please leave this value empty:
	// When the Type value is partial/full, the acceleration region of the L7 domain name. The following are the values of this parameter, and the default value is overseas if not filled in. When the Type value is noDomainAccess, please leave this value empty:
	// - global: Global availability zone.
	// - mainland: Chinese mainland availability zone.
	// - overseas: Global availability zone (excluding Chinese mainland).
	Area *string `json:"area,omitempty" tf:"area,omitempty"`

	// ID of the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// NS list allocated by Tencent Cloud.
	// NS list allocated by Tencent Cloud.
	NameServers []*string `json:"nameServers,omitempty" tf:"name_servers,omitempty"`

	// Ownership verification information. Note: This field may return null, indicating that no valid value can be obtained.
	// Ownership verification information. Note: This field may return null, indicating that no valid value can be obtained.
	OwnershipVerification []OwnershipVerificationObservation `json:"ownershipVerification,omitempty" tf:"ownership_verification,omitempty"`

	// Indicates whether the site is disabled.
	// Indicates whether the site is disabled.
	Paused *bool `json:"paused,omitempty" tf:"paused,omitempty"`

	// The target Plan ID to be bound. When you have an existing Plan in your account, you can fill in this parameter to directly bind the site to the Plan. If you do not have a Plan that can be bound at the moment, please go to the console to purchase a Plan to complete the site creation.
	// The target Plan ID to be bound. When you have an existing Plan in your account, you can fill in this parameter to directly bind the site to the Plan. If you do not have a Plan that can be bound at the moment, please go to the console to purchase a Plan to complete the site creation.
	PlanID *string `json:"planId,omitempty" tf:"plan_id,omitempty"`

	// Site status. Valid values: active: NS is switched; pending: NS is not switched; moved: NS is moved; deactivated: this site is blocked.
	// Site status. Valid values: `active`: NS is switched; `pending`: NS is not switched; `moved`: NS is moved; `deactivated`: this site is blocked.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Tag description list.
	// Tag description list.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Site Access Type. The possible values for this parameter are as follows; if left unspecified, the default value is partial:
	// Site Access Type. The possible values for this parameter are as follows; if left unspecified, the default value is `partial`:
	//
	// - `partial`: CNAME Access;
	// - `full`: NS Access;
	// - `noDomainAccess`: No-Domain Access;
	// - `dnsPodAccess`: DNSPod Managed Access (this mode requires your domain to already be hosted on DNSPod);
	// - `ai`: Edge Inference Access.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Configuration group work mode. Each configuration module of the site can enable version control mode or immediate effect mode according to the configuration group dimension. For details, please refer to Version Management.
	// Configuration group work mode. Each configuration module of the site can enable version control mode or immediate effect mode according to the configuration group dimension. For details, please refer to [Version Management](https://cloud.tencent.com/document/product/1552/113690).
	WorkModeInfos []WorkModeInfosObservation `json:"workModeInfos,omitempty" tf:"work_mode_infos,omitempty"`

	// Site ID.
	// Site ID.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Site name. When accessing CNAME/NS, please pass the second-level domain (example.com) as the site name; when accessing without a domain name, please leave this value empty.
	// Site name. When accessing CNAME/NS, please pass the second-level domain (example.com) as the site name; when accessing without a domain name, please leave this value empty.
	ZoneName *string `json:"zoneName,omitempty" tf:"zone_name,omitempty"`
}

type ZoneParameters struct {

	// Alias site identifier. Limit the input to a combination of numbers, English, - and _, within 20 characters. For details, refer to the alias site identifier. If there is no such usage scenario, leave this field empty.
	// Alias site identifier. Limit the input to a combination of numbers, English, - and _, within 20 characters. For details, refer to the alias site identifier. If there is no such usage scenario, leave this field empty.
	// +kubebuilder:validation:Optional
	AliasZoneName *string `json:"aliasZoneName,omitempty" tf:"alias_zone_name,omitempty"`

	// When the Type value is partial/full, the acceleration region of the L7 domain name. The following are the values of this parameter, and the default value is overseas if not filled in. When the Type value is noDomainAccess, please leave this value empty:
	// When the Type value is partial/full, the acceleration region of the L7 domain name. The following are the values of this parameter, and the default value is overseas if not filled in. When the Type value is noDomainAccess, please leave this value empty:
	// - global: Global availability zone.
	// - mainland: Chinese mainland availability zone.
	// - overseas: Global availability zone (excluding Chinese mainland).
	// +kubebuilder:validation:Optional
	Area *string `json:"area,omitempty" tf:"area,omitempty"`

	// Indicates whether the site is disabled.
	// Indicates whether the site is disabled.
	// +kubebuilder:validation:Optional
	Paused *bool `json:"paused,omitempty" tf:"paused,omitempty"`

	// The target Plan ID to be bound. When you have an existing Plan in your account, you can fill in this parameter to directly bind the site to the Plan. If you do not have a Plan that can be bound at the moment, please go to the console to purchase a Plan to complete the site creation.
	// The target Plan ID to be bound. When you have an existing Plan in your account, you can fill in this parameter to directly bind the site to the Plan. If you do not have a Plan that can be bound at the moment, please go to the console to purchase a Plan to complete the site creation.
	// +kubebuilder:validation:Optional
	PlanID *string `json:"planId,omitempty" tf:"plan_id,omitempty"`

	// Tag description list.
	// Tag description list.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Site Access Type. The possible values for this parameter are as follows; if left unspecified, the default value is partial:
	// Site Access Type. The possible values for this parameter are as follows; if left unspecified, the default value is `partial`:
	//
	// - `partial`: CNAME Access;
	// - `full`: NS Access;
	// - `noDomainAccess`: No-Domain Access;
	// - `dnsPodAccess`: DNSPod Managed Access (this mode requires your domain to already be hosted on DNSPod);
	// - `ai`: Edge Inference Access.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Configuration group work mode. Each configuration module of the site can enable version control mode or immediate effect mode according to the configuration group dimension. For details, please refer to Version Management.
	// Configuration group work mode. Each configuration module of the site can enable version control mode or immediate effect mode according to the configuration group dimension. For details, please refer to [Version Management](https://cloud.tencent.com/document/product/1552/113690).
	// +kubebuilder:validation:Optional
	WorkModeInfos []WorkModeInfosParameters `json:"workModeInfos,omitempty" tf:"work_mode_infos,omitempty"`

	// Site name. When accessing CNAME/NS, please pass the second-level domain (example.com) as the site name; when accessing without a domain name, please leave this value empty.
	// Site name. When accessing CNAME/NS, please pass the second-level domain (example.com) as the site name; when accessing without a domain name, please leave this value empty.
	// +kubebuilder:validation:Optional
	ZoneName *string `json:"zoneName,omitempty" tf:"zone_name,omitempty"`
}

// ZoneSpec defines the desired state of Zone
type ZoneSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ZoneParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ZoneInitParameters `json:"initProvider,omitempty"`
}

// ZoneStatus defines the observed state of Zone.
type ZoneStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ZoneObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Zone is the Schema for the Zones API. Provides a resource to create a teo zone
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,tencentcloud}
type Zone struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.area) || (has(self.initProvider) && has(self.initProvider.area))",message="spec.forProvider.area is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.planId) || (has(self.initProvider) && has(self.initProvider.planId))",message="spec.forProvider.planId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zoneName) || (has(self.initProvider) && has(self.initProvider.zoneName))",message="spec.forProvider.zoneName is a required parameter"
	Spec   ZoneSpec   `json:"spec"`
	Status ZoneStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ZoneList contains a list of Zones
type ZoneList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Zone `json:"items"`
}

// Repository type metadata.
var (
	Zone_Kind             = "Zone"
	Zone_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Zone_Kind}.String()
	Zone_KindAPIVersion   = Zone_Kind + "." + CRDGroupVersion.String()
	Zone_GroupVersionKind = CRDGroupVersion.WithKind(Zone_Kind)
)

func init() {
	SchemeBuilder.Register(&Zone{}, &ZoneList{})
}
