apiVersion: cos.tencentcloud.crossplane.io/v1alpha1
kind: BucketDomainCertificateAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: cos/v1alpha1/bucketdomaincertificateattachment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    domainCertificate:
    - certificate:
      - certType: CustomCert
        customCert:
        - certId: JG65alUy
          certSecretRef:
            key: example-key
            name: example-secret
            namespace: upbound-system
          privateKeySecretRef:
            key: example-key
            name: example-secret
            namespace: upbound-system
      domain: ${var.custom_origin_domain}

---

apiVersion: cos.tencentcloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: cos/v1alpha1/bucketdomaincertificateattachment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    acl: private
    bucket: private-bucket-${local.app_id}
    forceClean: true
    originDomainRules:
    - domain: ${var.custom_origin_domain}
      status: ENABLED
      type: REST
