apiVersion: kafka.tencentcloud.crossplane.io/v1alpha1
kind: Acl
metadata:
  annotations:
    meta.upbound.io/example-id: kafka/v1alpha1/acl
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    host: '*'
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    operationType: WRITE
    permissionType: ALLOW
    principal: ${tencentcloud_ckafka_user.example.account_name}
    resourceName: tf-example-resource
    resourceType: TOPIC

---

apiVersion: kafka.tencentcloud.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: kafka/v1alpha1/acl
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountName: tf-example
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
