apiVersion: tcr.tencentcloud.crossplane.io/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: tcr/v1alpha1/repository
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    briefDesc: desc.
    description: description.
    forceDelete: true
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: tf-example
    namespaceName: example

---

apiVersion: tcr.tencentcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: tcr/v1alpha1/repository
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    deleteBucket: true
    instanceType: standard
    name: tf-example
    tags:
      createdBy: Terraform

---

apiVersion: tcr.tencentcloud.crossplane.io/v1alpha1
kind: TcrNamespace
metadata:
  annotations:
    meta.upbound.io/example-id: tcr/v1alpha1/repository
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    instanceId: ${tencentcloud_tcr_instance.example.id}
    name: tf_example
    severity: medium
