/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AnonymousAccessInitParameters struct {

	// Operation list, supporting trackLog (JS/HTTP upload log) and realtimeProducer (kafka protocol upload log).
	// Operation list, supporting trackLog (JS/HTTP upload log) and realtimeProducer (kafka protocol upload log).
	Conditions []ConditionsInitParameters `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// Operation list, supporting trackLog (JS/HTTP upload log) and realtimeProducer (kafka protocol upload log).
	// Operation list, supporting trackLog (JS/HTTP upload log) and realtimeProducer (kafka protocol upload log).
	Operations []*string `json:"operations,omitempty" tf:"operations,omitempty"`
}

type AnonymousAccessObservation struct {

	// Operation list, supporting trackLog (JS/HTTP upload log) and realtimeProducer (kafka protocol upload log).
	// Operation list, supporting trackLog (JS/HTTP upload log) and realtimeProducer (kafka protocol upload log).
	Conditions []ConditionsObservation `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// Operation list, supporting trackLog (JS/HTTP upload log) and realtimeProducer (kafka protocol upload log).
	// Operation list, supporting trackLog (JS/HTTP upload log) and realtimeProducer (kafka protocol upload log).
	Operations []*string `json:"operations,omitempty" tf:"operations,omitempty"`
}

type AnonymousAccessParameters struct {

	// Operation list, supporting trackLog (JS/HTTP upload log) and realtimeProducer (kafka protocol upload log).
	// Operation list, supporting trackLog (JS/HTTP upload log) and realtimeProducer (kafka protocol upload log).
	// +kubebuilder:validation:Optional
	Conditions []ConditionsParameters `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// Operation list, supporting trackLog (JS/HTTP upload log) and realtimeProducer (kafka protocol upload log).
	// Operation list, supporting trackLog (JS/HTTP upload log) and realtimeProducer (kafka protocol upload log).
	// +kubebuilder:validation:Optional
	Operations []*string `json:"operations,omitempty" tf:"operations,omitempty"`
}

type ConditionsInitParameters struct {

	// Condition attribute, currently only VpcID is supported.
	// Condition attribute, currently only VpcID is supported.
	Attributes *string `json:"attributes,omitempty" tf:"attributes,omitempty"`

	// The value of the corresponding conditional attribute.
	// The value of the corresponding conditional attribute.
	ConditionValue *string `json:"conditionValue,omitempty" tf:"condition_value,omitempty"`

	// Conditional rule, 1: equal, 2: not equal.
	// Conditional rule, 1: equal, 2: not equal.
	Rule *float64 `json:"rule,omitempty" tf:"rule,omitempty"`
}

type ConditionsObservation struct {

	// Condition attribute, currently only VpcID is supported.
	// Condition attribute, currently only VpcID is supported.
	Attributes *string `json:"attributes,omitempty" tf:"attributes,omitempty"`

	// The value of the corresponding conditional attribute.
	// The value of the corresponding conditional attribute.
	ConditionValue *string `json:"conditionValue,omitempty" tf:"condition_value,omitempty"`

	// Conditional rule, 1: equal, 2: not equal.
	// Conditional rule, 1: equal, 2: not equal.
	Rule *float64 `json:"rule,omitempty" tf:"rule,omitempty"`
}

type ConditionsParameters struct {

	// Condition attribute, currently only VpcID is supported.
	// Condition attribute, currently only VpcID is supported.
	// +kubebuilder:validation:Optional
	Attributes *string `json:"attributes,omitempty" tf:"attributes,omitempty"`

	// The value of the corresponding conditional attribute.
	// The value of the corresponding conditional attribute.
	// +kubebuilder:validation:Optional
	ConditionValue *string `json:"conditionValue,omitempty" tf:"condition_value,omitempty"`

	// Conditional rule, 1: equal, 2: not equal.
	// Conditional rule, 1: equal, 2: not equal.
	// +kubebuilder:validation:Optional
	Rule *float64 `json:"rule,omitempty" tf:"rule,omitempty"`
}

type ExtendsInitParameters struct {

	// Log topic authentication free configuration information.
	// Log topic authentication free configuration information.
	AnonymousAccess []AnonymousAccessInitParameters `json:"anonymousAccess,omitempty" tf:"anonymous_access,omitempty"`
}

type ExtendsObservation struct {

	// Log topic authentication free configuration information.
	// Log topic authentication free configuration information.
	AnonymousAccess []AnonymousAccessObservation `json:"anonymousAccess,omitempty" tf:"anonymous_access,omitempty"`
}

type ExtendsParameters struct {

	// Log topic authentication free configuration information.
	// Log topic authentication free configuration information.
	// +kubebuilder:validation:Optional
	AnonymousAccess []AnonymousAccessParameters `json:"anonymousAccess,omitempty" tf:"anonymous_access,omitempty"`
}

type TopicInitParameters struct {

	// Whether to enable automatic split. Default value: true.
	// Whether to enable automatic split. Default value: true.
	AutoSplit *bool `json:"autoSplit,omitempty" tf:"auto_split,omitempty"`

	// Log Topic Description.
	// Log Topic Description.
	Describes *string `json:"describes,omitempty" tf:"describes,omitempty"`

	// Encryption-related parameters. This parameter is supported for users with an open access list and from encrypted regions; it cannot be passed in other scenarios. 0 or not passed: No encryption. 1: KMS-CLS cloud product key encryption. Once enabled, it cannot be disabled.
	// Supported regions: ap-beijing, ap-guangzhou, ap-shanghai, ap-singapore, ap-bangkok, ap-jakarta, eu-frankfurt, ap-seoul, ap-tokyo.
	// Encryption-related parameters. This parameter is supported for users with an open access list and from encrypted regions; it cannot be passed in other scenarios. 0 or not passed: No encryption. 1: KMS-CLS cloud product key encryption. Once enabled, it cannot be disabled.
	// Supported regions: ap-beijing, ap-guangzhou, ap-shanghai, ap-singapore, ap-bangkok, ap-jakarta, eu-frankfurt, ap-seoul, ap-tokyo.
	Encryption *float64 `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// Log Subject Extension Information.
	// Log Subject Extension Information.
	Extends []ExtendsInitParameters `json:"extends,omitempty" tf:"extends,omitempty"`

	// 0: Turn off log sinking. Non 0: The number of days of standard storage after enabling log settling. HotPeriod needs to be greater than or equal to 7 and less than Period. Only effective when StorageType is hot.
	// 0: Turn off log sinking. Non 0: The number of days of standard storage after enabling log settling. HotPeriod needs to be greater than or equal to 7 and less than Period. Only effective when StorageType is hot.
	HotPeriod *float64 `json:"hotPeriod,omitempty" tf:"hot_period,omitempty"`

	// No authentication switch. False: closed; True: Enable. The default is false. After activation, anonymous access to the log topic will be supported for specified operations.
	// No authentication switch. False: closed; True: Enable. The default is false. After activation, anonymous access to the log topic will be supported for specified operations.
	IsWebTracking *bool `json:"isWebTracking,omitempty" tf:"is_web_tracking,omitempty"`

	// Logset ID.
	// Logset ID.
	// +crossplane:generate:reference:type=Logset
	LogsetID *string `json:"logsetId,omitempty" tf:"logset_id,omitempty"`

	// Reference to a Logset to populate logsetId.
	// +kubebuilder:validation:Optional
	LogsetIDRef *v1.Reference `json:"logsetIdRef,omitempty" tf:"-"`

	// Selector for a Logset to populate logsetId.
	// +kubebuilder:validation:Optional
	LogsetIDSelector *v1.Selector `json:"logsetIdSelector,omitempty" tf:"-"`

	// Maximum number of partitions to split into for this topic if automatic split is enabled. Default value: 50.
	// Maximum number of partitions to split into for this topic if automatic split is enabled. Default value: 50.
	MaxSplitPartitions *float64 `json:"maxSplitPartitions,omitempty" tf:"max_split_partitions,omitempty"`

	// Number of log topic partitions. Default value: 1. Maximum value: 10.
	// Number of log topic partitions. Default value: 1. Maximum value: 10.
	PartitionCount *float64 `json:"partitionCount,omitempty" tf:"partition_count,omitempty"`

	// lifetime. Unit: days. Standard storage value range: 1 to 3600. Infrequent storage value range: 7 to 3600 days. A value of 3640 indicates permanent retention.If this value is not input, it defaults to the Period value of the log set corresponding to the accessed log topic (defaults to 30 days in case of access failure).
	// lifetime. Unit: days. Standard storage value range: 1 to 3600. Infrequent storage value range: 7 to 3600 days. A value of 3640 indicates permanent retention.If this value is not input, it defaults to the Period value of the log set corresponding to the accessed log topic (defaults to 30 days in case of access failure).
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// Log topic storage class. Valid values: hot: real-time storage; cold: offline storage. Default value: hot. If cold is passed in, please contact the customer service to add the log topic to the allowlist first.
	// Log topic storage class. Valid values: hot: real-time storage; cold: offline storage. Default value: hot. If cold is passed in, please contact the customer service to add the log topic to the allowlist first.
	StorageType *string `json:"storageType,omitempty" tf:"storage_type,omitempty"`

	// Tag description list. Up to 10 tag key-value pairs are supported and must be unique.
	// Tag description list. Up to 10 tag key-value pairs are supported and must be unique.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Log topic name.
	// Log topic name.
	TopicName *string `json:"topicName,omitempty" tf:"topic_name,omitempty"`
}

type TopicObservation struct {

	// Whether to enable automatic split. Default value: true.
	// Whether to enable automatic split. Default value: true.
	AutoSplit *bool `json:"autoSplit,omitempty" tf:"auto_split,omitempty"`

	// Log Topic Description.
	// Log Topic Description.
	Describes *string `json:"describes,omitempty" tf:"describes,omitempty"`

	// Encryption-related parameters. This parameter is supported for users with an open access list and from encrypted regions; it cannot be passed in other scenarios. 0 or not passed: No encryption. 1: KMS-CLS cloud product key encryption. Once enabled, it cannot be disabled.
	// Supported regions: ap-beijing, ap-guangzhou, ap-shanghai, ap-singapore, ap-bangkok, ap-jakarta, eu-frankfurt, ap-seoul, ap-tokyo.
	// Encryption-related parameters. This parameter is supported for users with an open access list and from encrypted regions; it cannot be passed in other scenarios. 0 or not passed: No encryption. 1: KMS-CLS cloud product key encryption. Once enabled, it cannot be disabled.
	// Supported regions: ap-beijing, ap-guangzhou, ap-shanghai, ap-singapore, ap-bangkok, ap-jakarta, eu-frankfurt, ap-seoul, ap-tokyo.
	Encryption *float64 `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// Log Subject Extension Information.
	// Log Subject Extension Information.
	Extends []ExtendsObservation `json:"extends,omitempty" tf:"extends,omitempty"`

	// 0: Turn off log sinking. Non 0: The number of days of standard storage after enabling log settling. HotPeriod needs to be greater than or equal to 7 and less than Period. Only effective when StorageType is hot.
	// 0: Turn off log sinking. Non 0: The number of days of standard storage after enabling log settling. HotPeriod needs to be greater than or equal to 7 and less than Period. Only effective when StorageType is hot.
	HotPeriod *float64 `json:"hotPeriod,omitempty" tf:"hot_period,omitempty"`

	// ID of the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// No authentication switch. False: closed; True: Enable. The default is false. After activation, anonymous access to the log topic will be supported for specified operations.
	// No authentication switch. False: closed; True: Enable. The default is false. After activation, anonymous access to the log topic will be supported for specified operations.
	IsWebTracking *bool `json:"isWebTracking,omitempty" tf:"is_web_tracking,omitempty"`

	// Logset ID.
	// Logset ID.
	LogsetID *string `json:"logsetId,omitempty" tf:"logset_id,omitempty"`

	// Maximum number of partitions to split into for this topic if automatic split is enabled. Default value: 50.
	// Maximum number of partitions to split into for this topic if automatic split is enabled. Default value: 50.
	MaxSplitPartitions *float64 `json:"maxSplitPartitions,omitempty" tf:"max_split_partitions,omitempty"`

	// Number of log topic partitions. Default value: 1. Maximum value: 10.
	// Number of log topic partitions. Default value: 1. Maximum value: 10.
	PartitionCount *float64 `json:"partitionCount,omitempty" tf:"partition_count,omitempty"`

	// lifetime. Unit: days. Standard storage value range: 1 to 3600. Infrequent storage value range: 7 to 3600 days. A value of 3640 indicates permanent retention.If this value is not input, it defaults to the Period value of the log set corresponding to the accessed log topic (defaults to 30 days in case of access failure).
	// lifetime. Unit: days. Standard storage value range: 1 to 3600. Infrequent storage value range: 7 to 3600 days. A value of 3640 indicates permanent retention.If this value is not input, it defaults to the Period value of the log set corresponding to the accessed log topic (defaults to 30 days in case of access failure).
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// Log topic storage class. Valid values: hot: real-time storage; cold: offline storage. Default value: hot. If cold is passed in, please contact the customer service to add the log topic to the allowlist first.
	// Log topic storage class. Valid values: hot: real-time storage; cold: offline storage. Default value: hot. If cold is passed in, please contact the customer service to add the log topic to the allowlist first.
	StorageType *string `json:"storageType,omitempty" tf:"storage_type,omitempty"`

	// Tag description list. Up to 10 tag key-value pairs are supported and must be unique.
	// Tag description list. Up to 10 tag key-value pairs are supported and must be unique.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Log topic name.
	// Log topic name.
	TopicName *string `json:"topicName,omitempty" tf:"topic_name,omitempty"`
}

type TopicParameters struct {

	// Whether to enable automatic split. Default value: true.
	// Whether to enable automatic split. Default value: true.
	// +kubebuilder:validation:Optional
	AutoSplit *bool `json:"autoSplit,omitempty" tf:"auto_split,omitempty"`

	// Log Topic Description.
	// Log Topic Description.
	// +kubebuilder:validation:Optional
	Describes *string `json:"describes,omitempty" tf:"describes,omitempty"`

	// Encryption-related parameters. This parameter is supported for users with an open access list and from encrypted regions; it cannot be passed in other scenarios. 0 or not passed: No encryption. 1: KMS-CLS cloud product key encryption. Once enabled, it cannot be disabled.
	// Supported regions: ap-beijing, ap-guangzhou, ap-shanghai, ap-singapore, ap-bangkok, ap-jakarta, eu-frankfurt, ap-seoul, ap-tokyo.
	// Encryption-related parameters. This parameter is supported for users with an open access list and from encrypted regions; it cannot be passed in other scenarios. 0 or not passed: No encryption. 1: KMS-CLS cloud product key encryption. Once enabled, it cannot be disabled.
	// Supported regions: ap-beijing, ap-guangzhou, ap-shanghai, ap-singapore, ap-bangkok, ap-jakarta, eu-frankfurt, ap-seoul, ap-tokyo.
	// +kubebuilder:validation:Optional
	Encryption *float64 `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// Log Subject Extension Information.
	// Log Subject Extension Information.
	// +kubebuilder:validation:Optional
	Extends []ExtendsParameters `json:"extends,omitempty" tf:"extends,omitempty"`

	// 0: Turn off log sinking. Non 0: The number of days of standard storage after enabling log settling. HotPeriod needs to be greater than or equal to 7 and less than Period. Only effective when StorageType is hot.
	// 0: Turn off log sinking. Non 0: The number of days of standard storage after enabling log settling. HotPeriod needs to be greater than or equal to 7 and less than Period. Only effective when StorageType is hot.
	// +kubebuilder:validation:Optional
	HotPeriod *float64 `json:"hotPeriod,omitempty" tf:"hot_period,omitempty"`

	// No authentication switch. False: closed; True: Enable. The default is false. After activation, anonymous access to the log topic will be supported for specified operations.
	// No authentication switch. False: closed; True: Enable. The default is false. After activation, anonymous access to the log topic will be supported for specified operations.
	// +kubebuilder:validation:Optional
	IsWebTracking *bool `json:"isWebTracking,omitempty" tf:"is_web_tracking,omitempty"`

	// Logset ID.
	// Logset ID.
	// +crossplane:generate:reference:type=Logset
	// +kubebuilder:validation:Optional
	LogsetID *string `json:"logsetId,omitempty" tf:"logset_id,omitempty"`

	// Reference to a Logset to populate logsetId.
	// +kubebuilder:validation:Optional
	LogsetIDRef *v1.Reference `json:"logsetIdRef,omitempty" tf:"-"`

	// Selector for a Logset to populate logsetId.
	// +kubebuilder:validation:Optional
	LogsetIDSelector *v1.Selector `json:"logsetIdSelector,omitempty" tf:"-"`

	// Maximum number of partitions to split into for this topic if automatic split is enabled. Default value: 50.
	// Maximum number of partitions to split into for this topic if automatic split is enabled. Default value: 50.
	// +kubebuilder:validation:Optional
	MaxSplitPartitions *float64 `json:"maxSplitPartitions,omitempty" tf:"max_split_partitions,omitempty"`

	// Number of log topic partitions. Default value: 1. Maximum value: 10.
	// Number of log topic partitions. Default value: 1. Maximum value: 10.
	// +kubebuilder:validation:Optional
	PartitionCount *float64 `json:"partitionCount,omitempty" tf:"partition_count,omitempty"`

	// lifetime. Unit: days. Standard storage value range: 1 to 3600. Infrequent storage value range: 7 to 3600 days. A value of 3640 indicates permanent retention.If this value is not input, it defaults to the Period value of the log set corresponding to the accessed log topic (defaults to 30 days in case of access failure).
	// lifetime. Unit: days. Standard storage value range: 1 to 3600. Infrequent storage value range: 7 to 3600 days. A value of 3640 indicates permanent retention.If this value is not input, it defaults to the Period value of the log set corresponding to the accessed log topic (defaults to 30 days in case of access failure).
	// +kubebuilder:validation:Optional
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// Log topic storage class. Valid values: hot: real-time storage; cold: offline storage. Default value: hot. If cold is passed in, please contact the customer service to add the log topic to the allowlist first.
	// Log topic storage class. Valid values: hot: real-time storage; cold: offline storage. Default value: hot. If cold is passed in, please contact the customer service to add the log topic to the allowlist first.
	// +kubebuilder:validation:Optional
	StorageType *string `json:"storageType,omitempty" tf:"storage_type,omitempty"`

	// Tag description list. Up to 10 tag key-value pairs are supported and must be unique.
	// Tag description list. Up to 10 tag key-value pairs are supported and must be unique.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Log topic name.
	// Log topic name.
	// +kubebuilder:validation:Optional
	TopicName *string `json:"topicName,omitempty" tf:"topic_name,omitempty"`
}

// TopicSpec defines the desired state of Topic
type TopicSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TopicParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TopicInitParameters `json:"initProvider,omitempty"`
}

// TopicStatus defines the observed state of Topic.
type TopicStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TopicObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Topic is the Schema for the Topics API. Provides a resource to create a cls topic.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,tencentcloud}
type Topic struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.topicName) || (has(self.initProvider) && has(self.initProvider.topicName))",message="spec.forProvider.topicName is a required parameter"
	Spec   TopicSpec   `json:"spec"`
	Status TopicStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TopicList contains a list of Topics
type TopicList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Topic `json:"items"`
}

// Repository type metadata.
var (
	Topic_Kind             = "Topic"
	Topic_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Topic_Kind}.String()
	Topic_KindAPIVersion   = Topic_Kind + "." + CRDGroupVersion.String()
	Topic_GroupVersionKind = CRDGroupVersion.WithKind(Topic_Kind)
)

func init() {
	SchemeBuilder.Register(&Topic{}, &TopicList{})
}
