apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: RouteEntry
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/routeentry
  labels:
    testing.upbound.io/example-name: example1
  name: example1
spec:
  forProvider:
    cidrBlock: 192.168.0.0/24
    nextHub: "0"
    nextType: eip
    routeTableIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: RouteTable
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/routeentry
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: tf-example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/routeentry
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    name: tf-example
