apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPNSSLServer
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vpnsslserver
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    localAddress:
    - 10.0.200.0/24
    remoteAddress: 192.168.100.0/24
    sslVpnServerName: helloworld
    vpnGatewayIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
